"""Copy the development database into the production one — deployment step 5.

    python -m worker.jobs.migrate_database                # the plan, and what the
                                                          # target holds right now
    python -m worker.jobs.migrate_database --self-test    # prove the byte path,
                                                          # no production needed
    python -m worker.jobs.migrate_database --execute      # move the data
    python -m worker.jobs.migrate_database --verify-only  # compare the two ends

Source is `SUPABASE_DB_URL`; target is `MIGRATION_TARGET_DB_URL`. Both are
secrets and neither is ever logged.

THIS IS NOT A RE-INGEST, and the difference is money. `player_prop_lines` holds
5,752 real closing lines bought for ~3,800 Odds API credits, and historical props
are sold per date rather than re-derived — a fresh backfill would come up
silently without them and every profitability number rests on them
(docs/deployment.md §5). So the data moves; it is not regenerated.

WHY BINARY COPY. `pg_dump` and `psql` do not exist on the machine this runs from,
but psycopg 3 streams a `COPY ... TO STDOUT (FORMAT BINARY)` straight into a
`COPY ... FROM STDIN (FORMAT BINARY)` on the other connection without the rows
ever being parsed into Python objects. Binary is safe across two databases *here*
specifically because the only user-defined types in the schema are scalar enums,
which travel as their label text, and the single array column (`backtests.seasons`)
is `int2[]` — a built-in element type whose OID is identical in every database.
An array of an enum or of a composite would embed a per-database OID and would
have to move as text instead. Check that before adding one.

FOUR THINGS THAT SILENTLY CORRUPT A COPY-BASED MIGRATION, all handled here:

  1. **Sequences.** Every `id` is `generated by default as identity`, so COPY
     happily writes explicit ids and leaves all 22 sequences sitting at 1. The
     first production insert then collides on the primary key. `reset_sequences`
     runs after the load and is not optional.
  2. **Generated columns.** `picks.confidence`, `picks.edge`,
     `picks.has_book_line` and `player_game_stats.offensive_tds` are STORED
     generated; COPY refuses to write them. They are excluded from the column
     list and recomputed by the target — and then checksummed, so the target's
     generation expressions are verified rather than assumed.
  3. **Surrogate ids that a fresh schema would renumber.** `sportsbooks` is NOT
     seeded by a migration — its rows were created at runtime by the odds
     adapter and carry gappy ids (1, 24, 25, 26, 27, 34, 39, 81). `conferences`
     IS seeded, but ingest has since grown it past the seed. Both are parents of
     data we are moving, so both are truncated and reloaded with their ids
     intact instead of being left as whatever the target's migrations produced.
  4. **`backtest_predictions` is not all-or-nothing.** See its entry in the plan.

Row triggers are not a problem: the nine `set_updated_at` triggers are BEFORE
UPDATE, and COPY inserts.
"""

from __future__ import annotations

import argparse
import os
import secrets
import sys
import time
from dataclasses import dataclass, field

import psycopg
from psycopg import sql
from psycopg.rows import dict_row

from worker.config import REPO_ROOT, ConfigError, get_settings
from worker.logging_setup import configure_logging, get_logger

log = get_logger(__name__)

JOB_NAME = "migrate_database"

TARGET_URL_ENV = "MIGRATION_TARGET_DB_URL"
SELF_TEST_SCHEMA = "migration_selftest"

# Rows per self-test table. Big enough to cover several COPY blocks, small
# enough that the scratch schema never threatens the source's 500 MB ceiling.
SELF_TEST_ROWS = 5_000

MIGRATIONS_DIR = REPO_ROOT / "supabase" / "migrations"


# =============================================================================
# The plan
# =============================================================================
@dataclass(frozen=True)
class TableSpec:
    """One table to move, in an order that satisfies its foreign keys.

    `where` filters the SOURCE side only. It applies to the copy, to the source
    row count and to the source checksum alike, so a filtered table verifies
    against what was actually asked for rather than against the whole table.
    """

    name: str
    reason: str
    where: str | None = None


# Ordered so that every table's parents load before it do. This is declared
# rather than derived at runtime, because an order a human can read is an order
# a human can check — and `test_migrate_database.py` proves it against the live
# foreign-key graph, so a migration that adds a table or an edge fails the test
# suite instead of failing the deployment.
PLAN: tuple[TableSpec, ...] = (
    TableSpec("conferences", "Parent of team_seasons. Migration-seeded AND grown "
                             "by ingest, so the target's seed is not enough."),
    TableSpec("venues", "Parent of games."),
    TableSpec("teams", "Parent of nearly everything."),
    TableSpec("team_seasons", "Read by the board for the conference filter."),
    TableSpec("games", "Parent of every per-game table; the week axis lives here."),
    TableSpec("game_weather", "Weather-adjusted projections (CLAUDE.md §7)."),
    TableSpec("game_lines", "Spread and total shown on the card. Re-ingestable "
                            "free from CFBD, unlike player_prop_lines below."),
    TableSpec("players", "Parent of every per-player table."),
    TableSpec("player_team_seasons", "Player-to-team mapping; the board joins through it."),
    TableSpec("markets", "Migration-seeded and identical, but moved so the two "
                         "databases are byte-comparable."),
    TableSpec("market_positions", "Which markets each position group shows."),
    TableSpec("sportsbooks", "NOT migration-seeded — runtime rows with gappy ids "
                             "that player_prop_lines points at."),
    TableSpec("app_config", "Runtime configuration (CLAUDE.md §9). Review "
                            "odds_adapter/ai_adapter on the target after the move."),
    TableSpec("model_runs", "Parent of projections and defense_position_ratings."),
    TableSpec("plays", "94 MB. Regenerable from CFBD, but that is hours and "
                       "thousands of calls."),
    TableSpec("play_player_stats", "82 MB. The position-split engine's input "
                                   "(CLAUDE.md §5), and read directly by the app."),
    TableSpec("player_game_stats", "Game logs and hit rates."),
    TableSpec("team_rating_snapshots", "Point-in-time ratings. Re-deriving these is "
                                       "where lookahead bias creeps in (CLAUDE.md §4)."),
    TableSpec("defense_position_game_splits", "Powers the defense-detail view."),
    TableSpec("defense_position_ratings", "Opponent-adjusted defensive ranks."),
    TableSpec("player_prop_lines", "IRREPLACEABLE. 5,752 bought closing lines that "
                                   "cannot be re-purchased."),
    TableSpec("projections", "Rebuildable by run_projections, but moving them means "
                             "the board is live the moment the site is."),
    TableSpec("picks", "Same. Also carries the generated confidence/edge columns "
                       "the target recomputes."),
    TableSpec("backtests", "MANDATORY. run_projections refuses to run without a "
                           "stored calibration snapshot and reads it from here."),
    TableSpec("backtest_metrics", "The headline numbers audit_data checks against "
                                  "the stored curve."),
    TableSpec("calibration_bins", "The calibration curve itself."),
    # Moving all 526,565 rows costs 129 MB on a 500 MB free tier. Moving none
    # fails three audit_data checks outright — "at least one backtest kept its
    # raw predictions", "the stored calibration curve reproduces from the raw
    # predictions" and "the walk grades the opening weeks the board publishes"
    # all resolve through the most recently persisted backtest_id, and an empty
    # table makes the first two vacuous-false and the third NULL. The middle
    # course is the only one that is both affordable and green: move exactly the
    # latest persisted run, whole. It must be whole — that second check
    # recomputes the reliability diagram from these rows and compares bin counts
    # exactly, so a partial copy fails it just as loudly as an empty one.
    TableSpec(
        "backtest_predictions",
        "The latest persisted walk only — ~35% of the rows, and what "
        "audit_data's three prediction-level checks resolve to.",
        where=(
            "backtest_id = (select backtest_id from backtest_predictions "
            "group by 1 order by max(created_at) desc limit 1)"
        ),
    ),
    TableSpec("ai_reads", "Cached weekly reads (CLAUDE.md §7). Empty while the adapter is 'none'."),
)

# Deliberately left behind. Anything in `public` that is in neither this dict nor
# PLAN fails the test suite, so a new table has to be a decision rather than an
# oversight.
SKIPPED: dict[str, str] = {
    "pipeline_runs": (
        "Development job history. Copying it would make production look as "
        "though jobs had run there when they never had, and monitor_pipeline "
        "reads exactly this table to decide what is stale — the wrong direction "
        "to be wrong in. Production starts with an honest empty history."
    ),
}


# =============================================================================
# Connections
# =============================================================================
# Pinned so that a row's text rendering — which is what the checksums hash — is
# identical on both ends regardless of what either database defaults to.
_SESSION_GUCS = (
    "set timezone to 'UTC'",
    "set datestyle to 'ISO, MDY'",
    "set extra_float_digits to 3",
)


def connect_to(url: str, *, autocommit: bool = False) -> psycopg.Connection:
    conn = psycopg.connect(url, autocommit=autocommit, row_factory=dict_row)
    with conn.cursor() as cur:
        for statement in _SESSION_GUCS:
            cur.execute(statement)
    if not autocommit:
        conn.commit()
    return conn


def _identity(conn: psycopg.Connection) -> dict[str, str]:
    """Host and database, for logging that names an end without leaking its password."""
    with conn.cursor() as cur:
        cur.execute(
            "select current_database() as db, "
            "coalesce(inet_server_addr()::text, 'local') as host, "
            "current_user as usr"
        )
        row = cur.fetchone()
    return {k: str(v) for k, v in (row or {}).items()}


def distinct_databases(
    src: psycopg.Connection, dst: psycopg.Connection
) -> tuple[bool, str]:
    """Prove the two ends are different databases — or refuse, rather than guess.

    NOT `system_identifier`, which is what this compared until 2026-08-09 and
    what every reference recommends. **Supabase provisions every project from
    one base image, so `pg_control_system()` reports the same identifier on
    unrelated projects.** Development `nqpmq…` and production `enpoq…` both
    report 7666007964130682852, and both report `pg_database.oid` 5, while one
    holds 28 tables and the other none. On the first real run the textbook
    identity test refused a correct migration, and it would have gone on
    refusing it. Neither of those values means anything here.

    Advisory locks are scoped to a database: a lock the source session holds is
    invisible from any other database and blocking from the same one. Taking it
    on one end and failing to re-take it on the other is therefore a proof
    rather than a comparison of values that may have been cloned — and it still
    writes nothing. The key is random per call so an unrelated process sitting
    on a fixed key cannot masquerade as the source and make two databases look
    like one.

    Returns (proved distinct, evidence). A probe that cannot run returns False:
    the caller must not proceed on an unproven guess, because the equal row
    counts of a same-database run sail straight through `check_direction`, and
    this is the only thing standing between that and a truncated source.
    """
    if src is dst:
        return False, "both ends are the same connection object"

    key = secrets.randbits(62) + 1
    try:
        with src.cursor() as cur:
            cur.execute("select pg_advisory_lock(%s)", (key,))
        try:
            with dst.cursor() as cur:
                cur.execute("select pg_try_advisory_lock(%s) as taken", (key,))
                taken = bool((cur.fetchone() or {}).get("taken"))
            if taken:
                with dst.cursor() as cur:
                    cur.execute("select pg_advisory_unlock(%s)", (key,))
        finally:
            # Session-level, so it outlives the rollback below and has to go
            # back explicitly. A leaked lock would fail the *next* run.
            with src.cursor() as cur:
                cur.execute("select pg_advisory_unlock(%s)", (key,))
    except psycopg.Error as exc:
        src.rollback()
        dst.rollback()
        return False, (
            f"the advisory-lock probe could not run ({exc.__class__.__name__}: "
            f"{exc}). It needs a session-mode connection on both ends — the "
            "6543 transaction pooler hands each statement to a different "
            "backend and cannot hold one. Nothing has been written."
        )

    src.rollback()
    dst.rollback()

    if not taken:
        return False, (
            "the target took an advisory lock the source is holding, so both "
            "DSNs address the SAME database. Truncating the target would "
            f"truncate the development data this migration exists to preserve. "
            f"{TARGET_URL_ENV} must be the production database."
        )
    return True, "advisory lock held on the source was free on the target"


# =============================================================================
# Catalog
# =============================================================================
@dataclass
class TableShape:
    copy_columns: list[str] = field(default_factory=list)
    check_columns: list[str] = field(default_factory=list)


def table_shape(conn: psycopg.Connection, table: str, schema: str = "public") -> TableShape:
    """Column lists in attnum order.

    Two of them: COPY may not write STORED generated columns, but the checksum
    covers them precisely so the target's generation expressions are verified
    rather than trusted.
    """
    with conn.cursor() as cur:
        cur.execute(
            """
            select a.attname, a.attgenerated
              from pg_class c
              join pg_namespace n on n.oid = c.relnamespace
              join pg_attribute a on a.attrelid = c.oid
             where n.nspname = %s and c.relname = %s
               and a.attnum > 0 and not a.attisdropped
             order by a.attnum
            """,
            (schema, table),
        )
        rows = cur.fetchall()
    if not rows:
        raise RuntimeError(f"{schema}.{table} does not exist")
    shape = TableShape()
    for row in rows:
        shape.check_columns.append(row["attname"])
        if not row["attgenerated"]:
            shape.copy_columns.append(row["attname"])
    return shape


def public_tables(conn: psycopg.Connection) -> set[str]:
    with conn.cursor() as cur:
        cur.execute(
            """
            select c.relname from pg_class c
              join pg_namespace n on n.oid = c.relnamespace
             where n.nspname = 'public' and c.relkind = 'r'
            """
        )
        return {r["relname"] for r in cur.fetchall()}


def foreign_key_edges(conn: psycopg.Connection) -> set[tuple[str, str]]:
    """(child, parent) pairs, self-references dropped."""
    with conn.cursor() as cur:
        cur.execute(
            """
            select src.relname as child, tgt.relname as parent
              from pg_constraint c
              join pg_class src on src.oid = c.conrelid
              join pg_class tgt on tgt.oid = c.confrelid
              join pg_namespace n on n.oid = src.relnamespace
             where c.contype = 'f' and n.nspname = 'public'
            """
        )
        return {
            (r["child"], r["parent"])
            for r in cur.fetchall()
            if r["child"] != r["parent"]
        }


def identity_sequences(
    conn: psycopg.Connection, tables: list[str], schema: str = "public"
) -> list[tuple[str, str]]:
    """(table, column) for every column backed by a sequence."""
    with conn.cursor() as cur:
        cur.execute(
            """
            select c.relname as tbl, a.attname as col
              from pg_class c
              join pg_namespace n on n.oid = c.relnamespace
              join pg_attribute a on a.attrelid = c.oid
             where n.nspname = %s and c.relkind = 'r'
               and c.relname = any(%s)
               and a.attnum > 0 and not a.attisdropped
               and pg_get_serial_sequence(quote_ident(n.nspname) || '.' ||
                                          quote_ident(c.relname), a.attname) is not null
             order by c.relname
            """,
            (schema, tables),
        )
        return [(r["tbl"], r["col"]) for r in cur.fetchall()]


# =============================================================================
# Measurement
# =============================================================================
def _source_relation(
    spec: TableSpec, columns: list[str], limit: int | None = None
) -> sql.Composed:
    stmt = sql.SQL("select {cols} from {tbl}").format(
        cols=sql.SQL(", ").join(sql.Identifier(c) for c in columns),
        tbl=sql.Identifier("public", spec.name),
    )
    if spec.where:
        stmt = sql.SQL("{base} where {pred}").format(base=stmt, pred=sql.SQL(spec.where))
    if limit is not None:
        # `order by ctid` because an unordered LIMIT picks whichever rows the
        # scan happens to reach first, and the self-test runs this query twice —
        # once to copy and once to checksum. Without the ordering a different
        # plan on the second pass compares two different 5,000-row samples and
        # reports a corruption that never happened. ctid is unique and stable
        # for a table nobody is writing to, and needs no knowledge of the key.
        stmt = sql.SQL("{base} order by ctid limit {n}").format(
            base=stmt, n=sql.Literal(limit)
        )
    return stmt


def checksum(conn: psycopg.Connection, relation: sql.Composed) -> tuple[int, int]:
    """(rows, order-independent hash of every column, generated ones included).

    `sum(hashtext(...))` rather than an ordered digest because it streams: the
    tables here run to hundreds of thousands of rows and aggregating them into
    one sorted array to hash would be the memory-hungriest thing in the job.
    """
    with conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                "select count(*) as n, "
                "coalesce(sum(hashtext(x::text)::bigint), 0) as h from ({rel}) x"
            ).format(rel=relation)
        )
        row = cur.fetchone() or {"n": 0, "h": 0}
    return int(row["n"]), int(row["h"])


def relation_size_mb(conn: psycopg.Connection, table: str) -> float:
    with conn.cursor() as cur:
        cur.execute(
            "select pg_total_relation_size(%s::regclass) / 1024.0 / 1024.0 as mb",
            (f"public.{table}",),
        )
        row = cur.fetchone()
    return float(row["mb"]) if row else 0.0


def database_size_mb(conn: psycopg.Connection) -> float:
    with conn.cursor() as cur:
        cur.execute("select pg_database_size(current_database()) / 1024.0 / 1024.0 as mb")
        row = cur.fetchone()
    return float(row["mb"]) if row else 0.0


def count_rows(conn: psycopg.Connection, table: str, schema: str = "public") -> int:
    with conn.cursor() as cur:
        cur.execute(
            sql.SQL("select count(*) as n from {}").format(sql.Identifier(schema, table))
        )
        row = cur.fetchone()
    return int(row["n"]) if row else 0


def count_selected(conn: psycopg.Connection, spec: TableSpec) -> int:
    """Rows the plan would actually move — the whole table unless it is filtered."""
    stmt = sql.SQL("select count(*) as n from {}").format(sql.Identifier("public", spec.name))
    if spec.where:
        stmt = sql.SQL("{base} where {pred}").format(base=stmt, pred=sql.SQL(spec.where))
    with conn.cursor() as cur:
        cur.execute(stmt)
        row = cur.fetchone()
    return int(row["n"]) if row else 0


# =============================================================================
# Pre-flight
# =============================================================================
# Enough of the plan to establish which end is which, without paying for a
# count on all 27 tables twice over a home connection. `player_prop_lines` is
# first because it is the one table whose loss is permanent.
_DIRECTION_WITNESSES = ("player_prop_lines", "plays", "projections", "players")


def check_direction(src: psycopg.Connection, dst: psycopg.Connection) -> list[str]:
    """Refuse to run the migration backwards.

    The failure this exists for: `SUPABASE_DB_URL` and `MIGRATION_TARGET_DB_URL`
    get swapped, the job dutifully truncates the DEVELOPMENT database and copies
    an empty production into it, and 5,752 closing lines that cost ~3,800 Odds
    API credits are gone — with no backup, because the free tier has none.

    `distinct_databases` cannot catch this; both ends really are distinct
    databases. The tell is the direction of the data: the source is the
    populated one.
    """
    problems: list[str] = []

    for table in _DIRECTION_WITNESSES:
        try:
            source_rows = count_rows(src, table)
            target_rows = count_rows(dst, table)
        except psycopg.Error:
            src.rollback()
            dst.rollback()
            continue

        if target_rows > source_rows:
            problems.append(
                f"{table}: the TARGET holds more rows than the SOURCE "
                f"({target_rows:,} vs {source_rows:,}). Either the two URLs are "
                "swapped — SUPABASE_DB_URL must be the development database and "
                f"{TARGET_URL_ENV} the production one — or the target is not as "
                "empty as expected. Nothing has been written."
            )

    if count_rows(src, "player_prop_lines") == 0:
        problems.append(
            "the source has no rows in player_prop_lines. That table holds the "
            "bought closing lines and is never empty on the development "
            "database, so this is almost certainly pointing at the wrong end."
        )

    return problems


def preflight(src: psycopg.Connection, dst: psycopg.Connection) -> list[str]:
    """Every reason not to proceed, gathered in one pass.

    All checks run even after one fails, because a first-time deployment wants
    the whole list rather than one problem per attempt.
    """
    problems: list[str] = check_direction(src, dst)

    ledger_files = sorted(p.name.split("_")[0] for p in MIGRATIONS_DIR.glob("*.sql"))
    with dst.cursor() as cur:
        try:
            cur.execute(
                "select version from supabase_migrations.schema_migrations order by version"
            )
            applied = [str(r["version"]) for r in cur.fetchall()]
        except psycopg.Error:
            dst.rollback()
            applied = []
    missing = [v for v in ledger_files if v not in set(applied)]
    if missing:
        problems.append(
            f"the target's migration ledger is missing {len(missing)} of "
            f"{len(ledger_files)} migrations (first: {missing[0]}). Apply them and "
            "record them — docs/runbook.md#applying-a-migration — before moving data."
        )

    src_tables = public_tables(src)
    dst_tables = public_tables(dst)
    absent = sorted({s.name for s in PLAN} - dst_tables)
    if absent:
        problems.append(f"the target is missing planned table(s): {', '.join(absent)}")

    unplanned = sorted(src_tables - {s.name for s in PLAN} - set(SKIPPED))
    if unplanned:
        problems.append(
            f"the source has table(s) the plan does not mention: {', '.join(unplanned)}. "
            "Add them to PLAN or to SKIPPED — silently leaving a table behind is how "
            "production ends up subtly incomplete."
        )

    for spec in PLAN:
        if spec.name not in dst_tables or spec.name not in src_tables:
            continue
        a = table_shape(src, spec.name)
        b = table_shape(dst, spec.name)
        if a.copy_columns != b.copy_columns:
            problems.append(
                f"{spec.name}: column lists differ between source and target "
                f"(source {a.copy_columns} vs target {b.copy_columns}). The two "
                "schemas are not at the same migration."
            )

    return problems


# =============================================================================
# The move
# =============================================================================
def copy_table(
    src: psycopg.Connection,
    dst: psycopg.Connection,
    spec: TableSpec,
    *,
    target_schema: str = "public",
    limit: int | None = None,
) -> tuple[int, int]:
    """Stream the source table into an already-empty target table.

    Emptying is `truncate_all`'s job, not this function's — see the note there
    for why it cannot be done per-table. Returns (rows, bytes), and commits.
    """
    if src is dst:
        # A COPY out and a COPY in are both open at the same moment, and one
        # connection serves one statement at a time. Sharing it does not raise —
        # it deadlocks, and a deadlock during a deployment reads as a slow
        # network. Even the self-test, which copies a database into itself,
        # opens a second connection.
        raise ValueError("copy_table needs two distinct connections, not one twice")

    shape = table_shape(src, spec.name)
    relation = _source_relation(spec, shape.copy_columns, limit)

    copy_out = sql.SQL("copy ({rel}) to stdout (format binary)").format(rel=relation)
    copy_in = sql.SQL("copy {tbl} ({cols}) from stdin (format binary)").format(
        tbl=sql.Identifier(target_schema, spec.name),
        cols=sql.SQL(", ").join(sql.Identifier(c) for c in shape.copy_columns),
    )

    written = 0
    with dst.cursor() as dcur:
        with src.cursor() as scur:
            with scur.copy(copy_out) as source, dcur.copy(copy_in) as sink:
                for block in source:
                    sink.write(block)
                    written += len(block)
    dst.commit()

    rows = count_rows(dst, spec.name, target_schema)
    return rows, written


def truncate_all(
    conn: psycopg.Connection,
    specs: tuple[TableSpec, ...] = PLAN,
    schema: str = "public",
) -> None:
    """Empty every planned table in ONE statement, so a re-run starts clean.

    It has to be one statement. Postgres refuses to `truncate` a table that any
    foreign key references — **whether or not the referencing table holds a
    row** — unless every referencing table is truncated in the same statement or
    CASCADE is used. So a per-table truncate inside the load loop dies on
    `conferences`, the very first table, against a target where the schema
    exists. CASCADE would work and is the wrong tool: it would silently reach
    tables the plan deliberately leaves alone.

    Naming all of them together is safe precisely because the plan is closed
    under "is a parent of" — `test_no_skipped_table_is_a_parent_of_a_planned_one`
    is what keeps that true.

    The consequence worth stating: this job is all-or-nothing. A run that dies
    halfway leaves the target partly loaded, and the fix is to run it again
    rather than to resume it.
    """
    if not specs:
        return
    with conn.cursor() as cur:
        cur.execute(
            sql.SQL("truncate {}").format(
                sql.SQL(", ").join(
                    sql.Identifier(schema, spec.name) for spec in specs
                )
            )
        )
    conn.commit()


def reset_sequences(
    conn: psycopg.Connection, tables: list[str], schema: str = "public"
) -> list[str]:
    """Point every identity sequence past the largest id that was loaded.

    Without this every sequence still reads 1 and the first production insert
    collides on a primary key that COPY filled in explicitly. `is_called=false`
    with `max+1` so the next value is exactly max+1 even for an empty table.
    """
    done: list[str] = []
    for table, column in identity_sequences(conn, tables, schema):
        with conn.cursor() as cur:
            cur.execute(
                sql.SQL(
                    "select setval("
                    "  pg_get_serial_sequence({qualified}, {col}),"
                    "  coalesce((select max({colid}) from {tbl}), 0) + 1,"
                    "  false) as v"
                ).format(
                    qualified=sql.Literal(f"{schema}.{table}"),
                    col=sql.Literal(column),
                    colid=sql.Identifier(column),
                    tbl=sql.Identifier(schema, table),
                )
            )
            row = cur.fetchone()
        done.append(f"{table}.{column} -> {row['v'] if row else '?'}")
    conn.commit()
    return done


def verify(
    src: psycopg.Connection,
    dst: psycopg.Connection,
    specs: tuple[TableSpec, ...] = PLAN,
    *,
    target_schema: str = "public",
    limit: int | None = None,
) -> list[tuple[str, bool, str]]:
    """Compare both ends column-for-column. Returns (table, ok, detail)."""
    results: list[tuple[str, bool, str]] = []
    for spec in specs:
        shape = table_shape(src, spec.name)
        src_rows, src_hash = checksum(src, _source_relation(spec, shape.check_columns, limit))

        dst_relation = sql.SQL("select {cols} from {tbl}").format(
            cols=sql.SQL(", ").join(sql.Identifier(c) for c in shape.check_columns),
            tbl=sql.Identifier(target_schema, spec.name),
        )
        dst_rows, dst_hash = checksum(dst, dst_relation)

        if src_rows != dst_rows:
            results.append(
                (spec.name, False, f"row count {src_rows:,} source vs {dst_rows:,} target")
            )
        elif src_hash != dst_hash:
            results.append(
                (spec.name, False, f"{src_rows:,} rows but the checksums differ")
            )
        else:
            results.append((spec.name, True, f"{src_rows:,} rows, checksums agree"))
    return results


# =============================================================================
# Modes
# =============================================================================
def render_plan(src: psycopg.Connection, dst: psycopg.Connection | None) -> float:
    """Print what would move. Returns the projected megabytes."""
    log.info("%-32s %10s %12s  %s", "TABLE", "ROWS", "SIZE", "TARGET NOW")
    total_mb = 0.0
    for spec in PLAN:
        rows = count_selected(src, spec)
        full = count_rows(src, spec.name)
        size = relation_size_mb(src, spec.name)
        moved_mb = size * (rows / full) if full else 0.0
        total_mb += moved_mb
        now = "-"
        if dst is not None:
            try:
                now = f"{count_rows(dst, spec.name):,} rows"
            except psycopg.Error:
                dst.rollback()
                now = "missing"
        suffix = f"  (of {full:,})" if rows != full else ""
        log.info("%-32s %10s %9.1f MB  %s%s", spec.name, f"{rows:,}", moved_mb, now, suffix)

    log.info("%-32s %10s %9.1f MB", "TOTAL", "", total_mb)
    for name, reason in SKIPPED.items():
        log.info("SKIPPED %s — %s", name, reason.split(".")[0].lower())
    log.info(
        "Source database is %.1f MB; roughly %.1f MB lands on the target, "
        "leaving ~%.0f MB under Supabase's 500 MB free-tier cap.",
        database_size_mb(src),
        total_mb,
        500 - total_mb,
    )
    return total_mb


def self_test(src: psycopg.Connection, url: str) -> int:
    """Run the real copy path source-to-source, into a scratch schema.

    The point is to exercise the actual bytes — binary COPY, enums, jsonb,
    int2[], numeric, STORED generated columns and the sequence reset — before
    the production database exists, so deployment night is not the first time
    this code has ever run. Small tables only: the source sits at ~448 MB of a
    500 MB cap and the scratch copies count against it.

    Takes the DSN as well as the open connection because it needs a SECOND one.
    A single connection runs a single statement at a time, and the whole point
    of this job is a `COPY TO STDOUT` feeding a `COPY FROM STDIN` — both live at
    once. Passing the same connection as both ends deadlocks rather than
    failing, which is a memorable way to learn it.
    """
    subset = tuple(
        s
        for s in PLAN
        if s.name
        in {
            "conferences",
            "venues",
            "teams",
            "team_seasons",
            "games",
            "game_weather",
            "markets",
            "market_positions",
            "sportsbooks",
            "app_config",
            "model_runs",
            "backtests",
            "backtest_metrics",
            "calibration_bins",
            # The only small table with STORED generated columns, and the one
            # that proves the target recomputes them to the same values.
            "player_game_stats",
        }
    )

    log.info(
        "Self-test: %d tables into schema %s, up to %s rows each.",
        len(subset),
        SELF_TEST_SCHEMA,
        f"{SELF_TEST_ROWS:,}",
    )
    sink = connect_to(url)
    try:
        with sink.cursor() as cur:
            cur.execute(
                sql.SQL("drop schema if exists {} cascade").format(
                    sql.Identifier(SELF_TEST_SCHEMA)
                )
            )
            cur.execute(sql.SQL("create schema {}").format(sql.Identifier(SELF_TEST_SCHEMA)))
            for spec in subset:
                # INCLUDING ALL carries defaults, identity, constraints and the
                # generated expressions — but not foreign keys, which is what
                # lets the subset be an arbitrary selection rather than a
                # closed one.
                cur.execute(
                    sql.SQL("create table {new} (like {old} including all)").format(
                        new=sql.Identifier(SELF_TEST_SCHEMA, spec.name),
                        old=sql.Identifier("public", spec.name),
                    )
                )
        sink.commit()

        truncate_all(sink, subset, SELF_TEST_SCHEMA)

        for spec in subset:
            rows, written = copy_table(
                src, sink, spec, target_schema=SELF_TEST_SCHEMA, limit=SELF_TEST_ROWS
            )
            log.info("  copied %-30s %8s rows  %6.1f MB", spec.name, f"{rows:,}", written / 1e6)

        moved = reset_sequences(sink, [s.name for s in subset], SELF_TEST_SCHEMA)
        log.info("  reset %d sequence(s)", len(moved))
        for entry in moved:
            log.info("    %s", entry)

        results = verify(src, sink, subset, target_schema=SELF_TEST_SCHEMA, limit=SELF_TEST_ROWS)
        failed = [r for r in results if not r[1]]
        for name, ok, detail in results:
            log.info("  [%s] %-30s %s", "PASS" if ok else "FAIL", name, detail)

        if failed:
            log.error("Self-test FAILED on %d table(s).", len(failed))
            return 1
        log.info("Self-test passed: the copy path is byte-exact on %d tables.", len(subset))
        return 0
    finally:
        sink.rollback()
        with sink.cursor() as cur:
            cur.execute(
                sql.SQL("drop schema if exists {} cascade").format(
                    sql.Identifier(SELF_TEST_SCHEMA)
                )
            )
        sink.commit()
        sink.close()
        log.info("Scratch schema dropped.")


def execute(src: psycopg.Connection, dst: psycopg.Connection) -> int:
    started = time.monotonic()
    total_bytes = 0

    log.info("Emptying %d target tables in one statement.", len(PLAN))
    truncate_all(dst)

    log.info("Loading %d tables in foreign-key order.", len(PLAN))
    for index, spec in enumerate(PLAN, start=1):
        table_started = time.monotonic()
        rows, written = copy_table(src, dst, spec)
        total_bytes += written
        log.info(
            "  [%2d/%2d] %-30s %10s rows  %7.1f MB  %5.1fs",
            index,
            len(PLAN),
            spec.name,
            f"{rows:,}",
            written / 1e6,
            time.monotonic() - table_started,
        )

    log.info("Resetting identity sequences.")
    for entry in reset_sequences(dst, [s.name for s in PLAN]):
        log.info("  %s", entry)

    log.info("Analysing the target so the planner has statistics.")
    dst.commit()
    dst.autocommit = True
    with dst.cursor() as cur:
        for spec in PLAN:
            cur.execute(sql.SQL("analyze {}").format(sql.Identifier("public", spec.name)))
    dst.autocommit = False

    log.info(
        "Moved %.1f MB in %.0fs. Target database is now %.1f MB.",
        total_bytes / 1e6,
        time.monotonic() - started,
        database_size_mb(dst),
    )

    return report_verification(verify(src, dst))


def report_verification(results: list[tuple[str, bool, str]]) -> int:
    failed = [r for r in results if not r[1]]
    for name, ok, detail in results:
        log.info("  [%s] %-30s %s", "PASS" if ok else "FAIL", name, detail)
    if failed:
        log.error(
            "%d of %d tables did not verify: %s",
            len(failed),
            len(results),
            ", ".join(name for name, _, _ in failed),
        )
        return 1
    log.info("All %d tables verified: row counts and checksums agree.", len(results))
    return 0


# =============================================================================
# Entry point
# =============================================================================
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Copy the development database into the production one.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Default is a dry run: it prints the plan and what the target holds "
            "now, and writes nothing. Use --self-test to prove the copy path "
            "without a production database at all."
        ),
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="actually move the data (truncates each target table first)",
    )
    parser.add_argument(
        "--verify-only",
        action="store_true",
        help="compare row counts and checksums without writing",
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help=f"round-trip a small subset into the source's own {SELF_TEST_SCHEMA} schema",
    )
    parser.add_argument(
        "--target-url-env",
        default=TARGET_URL_ENV,
        help=f"environment variable holding the target DSN (default {TARGET_URL_ENV})",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    try:
        settings = get_settings()
    except ConfigError as exc:
        configure_logging("INFO")
        log.error("Configuration error: %s", exc)
        return 2

    configure_logging(settings.log_level)

    src = connect_to(settings.database_url)
    try:
        log.info("Source: %s", _identity(src))

        if args.self_test:
            return self_test(src, settings.database_url)

        target_url = os.environ.get(args.target_url_env)
        if not target_url:
            # A dry run is still worth something with no target — it is the
            # answer to "how much are we about to move, and does it fit under
            # the free tier's 500 MB", which is a question worth answering
            # before the production database exists rather than after.
            if not args.execute and not args.verify_only:
                log.warning(
                    "%s is not set — showing the source side of the plan only.",
                    args.target_url_env,
                )
                render_plan(src, None)
                return 0
            log.error(
                "%s is not set. Put the target's Session pooler DSN (port 5432, "
                "not the 6543 transaction pooler and not the IPv6-only direct "
                "connection) in .env, which is gitignored. Or run --self-test, "
                "which needs no target at all.",
                args.target_url_env,
            )
            return 2

        dst = connect_to(target_url)
        try:
            log.info("Target: %s", _identity(dst))

            distinct, evidence = distinct_databases(src, dst)
            if not distinct:
                log.error("Refusing to run: %s", evidence)
                return 2
            log.debug("Distinct databases: %s.", evidence)

            problems = preflight(src, dst)
            if problems:
                for problem in problems:
                    log.error("pre-flight: %s", problem)
                return 2
            log.info("Pre-flight passed: same schema, ledger complete, distinct databases.")

            if args.verify_only:
                return report_verification(verify(src, dst))

            projected = render_plan(src, dst)
            if not args.execute:
                log.info(
                    "Dry run. Nothing was written. Re-run with --execute to move "
                    "the %.0f MB above.",
                    projected,
                )
                return 0

            return execute(src, dst)
        finally:
            dst.close()
    finally:
        src.close()


if __name__ == "__main__":
    sys.exit(main())
